<?php
namespace GestionEJBundle\Repository;
/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherparButs()
    {
        $em=$this->getEntityManager()->createQuery("SELECT m from GestionEJBundle:Joueur m ORDER BY m.buts DESC ");
        $a=$em->setMaxResults(8);
        return $a->getResult();
    }
    public function afficherparCout()
    {
        $em=$this->getEntityManager()->createQuery("SELECT m from GestionEJBundle:Joueur m ORDER BY m.cout DESC ");
        $a=$em->setMaxResults(6);
        return $a->getResult();
    }
}