<?php
namespace GestionEJBundle\Repository;
/**
 * StadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadeRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherDistinct()
    {
        $em=$this->getEntityManager()->createQuery("SELECT DISTINCT m.ville from GestionEJBundle:Stade m ");

        return $em->getResult();
    }

}