<?php

namespace GestionActualiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    public function DQL()
    {
           $em = $this->getEntityManager()->createQuery("select D from GestionActualiteBundle:Post D ORDER BY D.date DESC ");

           return $em->getResult();
    }

    public function recherche($post )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('GestionActualiteBundle:Post', 'a')
            ->where("a.title LIKE :post ")
            ->setParameter('post', '%'.$post.'%');
        echo "repostorie==".$post;
        return $qb->getQuery()
            ->getResult();
    }
}
