<?php

namespace GestionCommoditeBundle\Controller;

use GestionCommoditeBundle\Entity\Commodite;
use GestionCommoditeBundle\Entity\GalerieCommodite;
use GestionCommoditeBundle\Form\GalerieCommoditeType;
use GestionCommoditeBundle\Form\GalerieupdateType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;


class GalerieCommoditeController extends Controller
{
    /**
     * @Route("/newGal")
     */
    public function newBackGalAction( Request $request)
    {
        $galerieCommodite = new GalerieCommodite();
        $form = $this->createForm(GalerieCommoditeType::class, $galerieCommodite);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $file = $galerieCommodite->getName();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
            $file->move(
                $this->getParameter('images_directory'),
                $fileName);
            $galerieCommodite->setName($fileName);
            $em->persist($galerieCommodite);
            $em->flush();
            // return $this->redirectToRoute('galeriecommodite_show', array('idGalerie' => $galerieCommodite->getIdgalerie()));
        }
        return $this->render('@GestionCommodite/TemplateAdmin/newGalerie.html.twig', array(
            'galerieCommodite' => $galerieCommodite,
            'form' => $form->createView(),
        ));
    }


    /**
     * @Route("/updateGal")
     */

    public function updateBackGalAction(Request $request, $idGalerie)
    {
        $em = $this->getDoctrine()->getManager();
        $galerieCommodite = $em->getRepository("GestionCommoditeBundle:GalerieCommodite")->find($idGalerie);
        $form = $this->createForm(GalerieupdateType::class, $galerieCommodite);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $galerieCommodite->getName();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
            $file->move(
                $this->getParameter('images_directory'),
                $fileName);
            $galerieCommodite->setName($fileName);
            $em->persist($galerieCommodite);
            $em->flush();
            return $this->redirectToRoute('galeriecommodite_show');
        };
        return $this->render('@GestionCommodite/TemplateAdmin/updateGalerie.html.twig',
            array('galerieCommodite' => $galerieCommodite, 'form' => $form->createView()

            ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/deleteGal")
     */
    public function deleteBackGalAction($idGalerie)
    {
        $em = $this->getDoctrine()->getManager();
        $commodite = $em->getRepository("GestionCommoditeBundle:GalerieCommodite")->find($idGalerie);
        $em->remove($commodite);
        $em->flush();
        return $this->redirectToRoute('commodite_show');
    }

    /**
     * @Route("/showGal")
     */
    public function showBackGalAction()
    {
        $em = $this->getDoctrine()->getManager();

        $galerieCommodite = $em->getRepository('GestionCommoditeBundle:GalerieCommodite')->findAll();
        return $this->render('@GestionCommodite/TemplateAdmin/showGalerie.html.twig', array(
            'galerieCommodite' => $galerieCommodite,
        ));
    }

}
