services:
#    my_app_user.example:
#        class: MyApp\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  redirect.after.login:
    class:  MyApp\UserBundle\Redirection\LoginAfterRedirection
    arguments: ["@router"]
